# Generated by Django 5.0 on 2023-12-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('ll', 'all'), ('the office', 'the office'), ('friends', 'friends'), ('suits', 'suits')], max_length=500),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
