# Generated by Django 5.0 on 2023-12-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default=None, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
